# deploy laravel app to cpanel on /home/lerolero/access-core
---
deployment:
  tasks:
    - export DEPLOYPATH=/home/lerolero/access-core.lerolero.com.ec
    - cp -r * $DEPLOYPATH
    # php artisan migrate --force
    - cd $DEPLOYPATH
    # check if composer is installed
    - if [ ! -f composer.phar ]; then
    - curl -sS https://getcomposer.org/installer | php
    - fi
    - php composer.phar install
    - php artisan migrate --force
    
