# deploy laravel app to cpanel on /home/lerolero/access-core
---
deployment:
  tasks:
    - export DEPLOYPATH=/home/lerolero/access-core
    - export DEPLOYURL=https://access-core.lerolero.com.ec/
    - export DEPLOYUSER=lerolero
    
