# copy all files in the directory to the /home/lerolero/access-core
# run npm install and npm run build (cpanel)
---
deployment:
  tasks:
    - export DEPLOYPATH=/home/lerolero/access-core
    - /bin/cp -r * $DEPLOYPATH
    - /usr/local/bin/npm install --prefix $DEPLOYPATH
    - /usr/local/bin/npm run build --prefix $DEPLOYPATH
    
