# deploy laravel app to cpanel on /home/lerolero/access-core
---
deployment:
  tasks:
    - export DEPLOYPATH=/home/lerolero/access-core.lerolero.com.ec
    - cp -r * $DEPLOYPATH
    # php artisan migrate --force
    - cd $DEPLOYPATH
    - /usr/local/bin/php /opt/cpanel/ea-php83/root/usr/bin/composer install
    
