# deploy laravel app to cpanel on /home/lerolero/access-core
---
deployment:
  tasks:
    - export DEPLOYPATH=/home/lerolero/access-core.lerolero.com.ec
    - cp -r * $DEPLOYPATH
    # php artisan migrate --force
    - cd $DEPLOYPATH
    - composer install
    - php artisan migrate --force
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache
    - php artisan optimize
    - php artisan queue:restart
    - php artisan storage:link
    - php artisan config:clear
    - php artisan route:clear
    - php artisan view:clear
    - php artisan optimize:clear
    - php artisan queue:restart
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache
    
